# Generated by Django 5.1.4 on 2025-02-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
