# Generated by Django 5.1.4 on 2025-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_inteligente', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
